### ISSUE TITLE
[Question] Register the same command class under a different name

### ISSUE THREAD

**Issue by dzineit** [aikar/commands#228]
My requirement is to have a command class be registered under different command names, but:

a) with the specific name used being accessible to the command executing code

b) with the names which the command is to be registered under being unknown until runtime (meaning I can't just list them as aliases)

Is this possible?

**Comment by MiniDigger** [comment]
mmmh, yes, kinda.

you basically need to implement a base command, but instead of using annotations you need to override the onRegister method and register your stuff yourself:
https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/BaseCommand.java#L237

acf wasn't really build with that in mind so its not really clean and I am not sure if acf is even the right tool for this. the point of acf is that you have static command signatures and stuff so that it can be intelligent with completions, validations and object mapping.

**Comment by dzineit** [comment]
Thanks, I'll look into this. I appreciate it's not ideal but ACF is perfect for most of my use case so I'd like to be able to do this with it too.

I have 5/6 different commands and only one of them requires this functionality so would be a shame to have to switch just to do that.

**Comment by dzineit** [comment]
Hmm. Shame BaseCommand(String cmd) constructor is being removed as I believe I could've done what I needed through that. However I could potentially do as follows:

- create various instances of my BaseCommand-extending class
- use reflection to set BaseCommand's commandName variable to the appropriate name for each instance, before registration
- use getName() to access this

Any thoughts @MiniDigger - is this viable?
