### ISSUE TITLE
java.lang.NoClassDefFoundError: co/aikar/timings/lib/TimingManager

### ISSUE THREAD

**Issue by TryHardDood** [aikar/commands#24]
You could shade this dependency into the repo's jar. :)

**Comment by aikar** [comment]
Why isn't your shading config shading it for you?

My plugin is shading it correctly, as well as @simpleauthority's.

I think you have a config error, please paste your compilers config.

**Comment by TryHardDood** [comment]
I commented it out because I switched to sources instead of gradle. But here is the config: https://github.com/TryHardDood/AdvancedKitsReloaded/blob/master/build.gradle

**Comment by simpleauthority** [comment]
I don't use Gradle so I can't comment on the syntax of your script, but I can verify there isn't anything wrong with ACF as my jars compile and work just fine.

**Comment by TryHardDood** [comment]
There's nothing wrong with it :) 
The problem is when I shade the timings api it does not contain the TimingManager class. Idk why

**Comment by MiniDigger** [comment]
I remember some weird behavior of the shadow plugin not shading transitive dependencies. 
the way I always used shadow was by shading every dependency of the compile scope and define everything I do not want to be shaded with compiledOnly.
but since that class is not in a transitive dependency it should work...
is it just that one class that doesn't get shaded or are all of the timings stuff missing?

**Comment by TryHardDood** [comment]
Apparently yes, when I view a class (in the commands) in intellij idea (which decompiles the repo jar) it should show the class in the imports, but it shows it as red due to its not found. 

Keep in mind I added both dependencies (commands, mctimings)

**Comment by TryHardDood** [comment]
When I decompile the timings minecraft jar i don't see MCTimer class. I'm using the latest version.

**Comment by TryHardDood** [comment]
Fixed. Gradle didn't updated the dependencies.
