### ISSUE TITLE
BaseCommand Memory leak

### ISSUE THREAD

**Issue by Grinderwolf** [aikar/commands#337]
BaseCommand holds the operation context of the last time the command was executed. I suspect this may be the cause of a memory leak. This includes the command issuer, which, in Bukkit, holds a reference to the CommandSender. In the case of a player executing a command, this causes the Player object to not be collected by the GC until somebody else runs the same command. On top of that, if the player was on a world no longer loaded on the server when they disconnected, a reference to the entire World object is kept.

**Comment by CyberFlameGO** [comment]
Oh dang yeah that’s pretty bad

**Comment by embeddedt** [comment]
Perhaps this can be fixed by using a `WeakReference` [here](https://github.com/aikar/commands/blob/f033dd9541eee468cb05a96db0097ea493f9ec5b/core/src/main/java/co/aikar/commands/CommandOperationContext.java#L35)?

**Comment by Akiranya** [comment]
I believe this has caused memory leak on my server.

I dumped the memory, and looked into the GC roots of an monster entity which is suspicious leaked by CommandIssuer.
There were 30000+ leaked monster entity actually in my mem snapshot. This would happen if some player runs a pig zombie farm and keeps farming all the day.

Pig zombies have anger and Minecraft stores the anger in the CraftPlayer object. And CommandIssuer stores a reference of CraftPlayer. So it makes all the pig zombie entity objects which had anger at the player ever retained in the memory. Restarting server wouldn't help much because it's just leaking too fast :\

Here is the evidence:

![image](https://user-images.githubusercontent.com/14846342/136684757-e643bb64-9237-4a26-896f-c061287ec937.png)

There were 30000+ leaked monster entity actually in my mem snapshot. This was one of the many

**Comment by kyngs** [comment]
Is there any update on this? This could potentially be pretty serious.

**Comment by aikar** [comment]
well 'could be' is def going to really vary on lots of variables. In the screenshot above it was due to the player having entity damage as last damage source holding refs to the world chain.

But the proper fix is relating to https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/BaseCommand.java#L544

in postCommandOperation above this need to set this back to null.

**Comment by aikar** [comment]
Also id like to note this issue is absolutely not 'major', it's been like this for many years with no one noticing. While leaking the player object isn't good like this, what this shows is that it's identified an issue in Spigot/Paper instead, in that the last damage cause can leak an entity reference which can reference no longer valid entities/worlds. 

An issue should be filed for Paper too, that the entity ref on the damage cause should likely be a weakref and also include an .isValid() check.

If this entity wasn't leaked on the damage cause, it would not have been such a heavy impact here.

I am unable to fix this issue myself as I don't have java dev environment set back up on new PC, but I have asked chicken if he can verify my fix doesn't break things when he has time.

A weak ref here isn't the solution, we ultimately just need to be clearing that thread local as the context object doesn't really serve any value post execution.

**Comment by chickeneer** [comment]
I have pushed up that fix. I tried to modify the javadoc description for the accessor method for the last context to reflect that it can be null outside of command execution altogether. Instead of just before it has run the first time.
