### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Chazmondo** [aikar/commands#39]
Testing around with @Syntax and this is what happens.

http://i.chazza.io/v9gvw.png

First is with no @Syntax while second is with:
`@Syntax("§3[§bRankVouchers§3] §7Use §b/voucher create <id>.")`

If this isn't a bug, could it be implemented?

Cheers!

**Comment by Chazmondo** [comment]
Found a 'bypass' to resolve this by setting parameters to @Optional and then doing the following:
```
if(param == null){
            sender.sendMessage("§7Usage: §b/cmd subcmd <param> [param2]");
            return;
        }
```

Still would be cool if we could directly do this :)

**Comment by chickeneer** [comment]
If you prefer that people use /voucher as their primary command. You should use that in your class constructor:
`super("voucher");`

Then you should name the first parameter in your command "id". Since that is what you apparently want displayed. 
```
@Subcommand("create")
void onCreate(Player player, String id) {
}
```

Then the usage will output as "Usage: /voucher create <id>".
Then you do not need to use the @Syntax annotation at all. The Syntax annotation is intended only to override messy parameter names.

"If this isn't a bug, could it be implemented?"
Could you then clarify what you mean by this? Even though I have provided a valid solution. I am confused what you see the issue is. More details please 😃

**Comment by Chazmondo** [comment]
You didn't have this solution when I posted it :P 
Hence why saying "If this isn't a bug, could it be implemented?" was put.

Even with nice params I get
http://i.chazza.io/qdhau.png

```
@Subcommand("give|g")
    public void onCreateCommand(CommandSender sender, OnlinePlayer player, @Optional String id, @Optional Integer amount) {
```

**Comment by chickeneer** [comment]
If I remember correctly, you are the one obfuscating your plugin? The original parameter names are lost when you do that and would not be available at runtime. So it is implemented.
If you want nice Syntax, you will have to do `@Syntax("<player> [id] [amount]")`

I do not know of another solution past that...

**Comment by Chazmondo** [comment]
I'm not obfuscating currently, this is a recode version with no obfuscation.

**Comment by chickeneer** [comment]
We will have to get Aikar's thoughts on the matter then. No idea why your
parameter names could be changed to arg1

**Comment by TryHardDood** [comment]
Maybe?
https://github.com/aikar/commands/wiki/Frequently-Asked-Questions#my-parameter-names-in-syntax-are-arg1-etc

**Comment by chickeneer** [comment]
Well. There ya go.

**Comment by Chazmondo** [comment]
That fixed it @TryHardDood cheers dude!
