### ISSUE TITLE
trying to autocomplete first argument, then allow user to type "set" and then autocomplete again

### ISSUE THREAD

**Issue by Paradis4432** [aikar/commands#392]
this is the command syntax i want 
`/aar (groupID) set (options) (value) `
for example
`/aar 1 set name "new name" `

my problem:
CommandCompletion works for subcommands, so you need to define a subcommand and then a command completion to that subcommand, but i cant find a way to then add a subcommand after the completion. 

IDEALLY i do something like this 

```
@CommandAlias("aarenas|aar")
public class TestCommand extends BaseCommand {
    @Default
    @CommandCompletion("@arenasIDS")
    public class onSet extends BaseCommand{
        @Subcommand("set")
        public class onSetValue extends BaseCommand{
            @Subcommand("name")
            public void onSetName(Player player, String name){
                // set name of arena to new name
            }

            @Subcommand("max")
            public void onSetMax(Player player, Integer max){
                // set max players of arena to new max
            }
        }

        @Subcommand("some other subcommand")
        // handle other subcommands

    }
```

**Comment by chickeneer** [comment]
Hey there. This feature does not currently exist on ACF. It is definitely the most frequently requested ACF feature, so it will probably be added eventually in some form.

Closing this due to other issues existing on the topic.
https://github.com/aikar/commands/issues/242

Not invalidating the legitimacy of your inquiry, just there isn't a solution and other issues address it already
