### ISSUE TITLE
[Question/Suggestion?] User input subcommand?

### ISSUE THREAD

**Issue by Trophonix** [aikar/commands#49]
Is there a way one could use the subcommand inner class/method structure to make one of the subcommands user input? For example, a command like:
```
/arena <arena name> spawn
```
or
```
/perms user <user name> group set <group name>
```

And if not, could this possibly be implemented?
Thanks!

**Comment by chickeneer** [comment]
Is there a way? No.
Should it be implemented? I do not think so.
Could it? Probably.

It is not a natural approach to commands. 
*Reason 1:* To have reasonable and predictable tab-completions. 
This could work for your `/arena` command example with the restriction that there are no commands that use a non arena-name 1st argument; like `/arena info` which would just access your current location. Because, then when you type `/arena`, then TAB; you will have info mixed in with all of the arena-names (getting lost). And if you leave out the arena-names from the tab-complete, how will they ever find that command?
The real trouble then, is you have to put safeguards up to prevent an arena sharing a name with one of your sub-commands.

*Reason 2*: Ambiguous unknown commands makes providing meaningful feedback difficult.
Extending from the previous scenario, if you have other subcommands other than just arena names; how would we know if they misspelled an arena or misspelled a subcommand.
But this all could be easily avoided by just switching the order around...

I would highly suggest doing these commands instead:
```
/arena spawn <arena name>
```
and
```
/perms set user group <user name> <group name>
```
Notice in that last example, you are telling the server what you plan on typing next, the user and then the group. Then you could even get a quicker command like `@CommandAlias("setusergr")` or similar making shorter commands:
```
/setusergr <user name> <group name>
```

So what if we throw out my reasons, and pursue how this would be implemented. Well, it is half-way already possible. For example,
```
@CommandAlias("arena)
@CommandCompletion("@arenas spawn")
void onArenaSpawn(Player player, ArenaObject arena, @Values("spawn") String spawn) { }
```
Now assuming you want to do others cmds other than spawn. You could add them to the Values annotation. Then, doing an `else if` check or `switch` to separate out to separate methods. 

How would these commands look like in the code? I do not know, not my request - nor would I request it. Perhaps you have some further explanation on how this would be useful over the current command creating options?

**Comment by Trophonix** [comment]
Is there functionality currently for somehow registering things like "@arenas" to refer to the list of arenas? 

As for an explanation of why this would be useful, I just think the arguments make more sense and look nicer in the order I'm trying for, and if I used the command framework for the base command and then had to switch on the rest of the arguments myself, I might as well not use a command framework.

**Comment by chickeneer** [comment]
You would need to define `@arenas` in your plugin in a class extending BukkitCommandCompletions (or PaperCommandCompletions if appropriate).

I think it would be possible that we could possible support some very basic version of what you suggestion, but it is working entirely backwards from the idea of subcommands. What you are suggesting is what I would call, gracefully handling unknown commands. In the sense that there is no well-defined stepped procedure through the lower levels of subcommands. If that is what you want, great - but tab-completions would be poor in comparison.

**Comment by chickeneer** [comment]
What you suggest are not SubCommands. In the spirit of pursing your feature suggestion; I have some possible syntax that the commands would look like.
```
@UnknownHandler("$area spawn")
void onAreasSpawn(Player player, AreaObject area) { }
```
Where the `$area` is intended to indicate the area parameter. Idk, it doesn't look right to me. Maybe someone could off of the idea. That is all I've got on the subject. I am hesitant to even suggest this possibility as mentioned prior, this does not seem like recommended command syntax.

**Comment by Trophonix** [comment]
Yeah, I'm not sure how it could be done nicely. If someone could figure something out, it could potentially be a useful feature, but I do see your point. I'm going to structure my commands with the arguments at the end.

**Comment by aikar** [comment]
To update what chicken said, you don't need to extend BukkitCommandCompletions, simply call `manager.getCommandCompletions().registerCompletion("arenas", (c) -> { });`

**Comment by aikar** [comment]
But yes `@UnknownHandler` is what you want to do here. It's not clean, but it's the only way to provide deterministic commands. What you're suggesting just wouldn't let us know what commands going to be executed for tab completions, and also drastically increases complexity to resolve what command at the point of execution, which would require us to 'try' nearly every command, which then gets into realms of pattern conflicts, and knowing which command was intended to know what syntax information to show and what errors due to failed context resolvers to show.

It's just not possible, and i don't think we need to really expand UnknownCommands abilities for it either. 

I suggest you go the subcommand route as chicken suggested, and you can use the last parameter as a form of "action" and add more things than spawn where applicable.
